#!/bin/bash

grep -E '<td>.+</td>' hwnwdseng.htm | sed -n '1~2!p' | sed 's/<[^>]*>//g' | cut -c 5- | tr '[:upper:]' '[:lower:]' | sed 's/`/'\''/g' | sed 's/, /\n/g' | sed 's/ /\n/g' | sed "s/.*[^pk'mnwlhaeiou].*//" | sort -u | sed '1d'
